"""init_all_fresh

Revision ID: 3083269580b0
Revises: 
Create Date: 2026-03-13 23:03:12.768859

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3083269580b0'
down_revision = '0000000000ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friend_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship')
    )
    op.create_index('ix_friendship_addressee', 'friendships', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendships_addressee_id'), 'friendships', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendships_requester_id'), 'friendships', ['requester_id'], unique=False)
    op.create_table('meeting_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('invite_type', sa.Enum('FRIEND', 'REPLACE', name='invite_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DEPOSIT_PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='invite_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'invitee_id', 'invite_type', name='uq_meeting_invite')
    )
    op.create_index(op.f('ix_meeting_invitations_invitee_id'), 'meeting_invitations', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_meeting_invitations_meeting_id'), 'meeting_invitations', ['meeting_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notif_type', sa.Enum('MEETING_CANCELLED', name='notif_type_enum'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('meeting_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('place', sa.String(length=200), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_schedules_meeting_id'), 'meeting_schedules', ['meeting_id'], unique=True)
    op.create_table('ticket_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.Enum('PURCHASE', 'CONSUME', 'REFUND', name='ticket_tx_type_enum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tickets_after', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_transactions_user_id'), 'ticket_transactions', ['user_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.Enum('CHARGE', 'DEPOSIT_HOLD', 'DEPOSIT_REFUND', 'WITHDRAW', 'WITHDRAW_DONE', 'ADMIN_ADJUST', name='wallet_tx_type_enum'), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('toss_order_id', sa.String(length=64), nullable=True),
    sa.Column('toss_payment_key', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_meeting_id'), 'wallet_transactions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_toss_order_id'), 'wallet_transactions', ['toss_order_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_tx_type'), 'wallet_transactions', ['tx_type'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_tx_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_toss_order_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_meeting_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_ticket_transactions_user_id'), table_name='ticket_transactions')
    op.drop_table('ticket_transactions')
    op.drop_index(op.f('ix_meeting_schedules_meeting_id'), table_name='meeting_schedules')
    op.drop_table('meeting_schedules')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_meeting_invitations_meeting_id'), table_name='meeting_invitations')
    op.drop_index(op.f('ix_meeting_invitations_invitee_id'), table_name='meeting_invitations')
    op.drop_table('meeting_invitations')
    op.drop_index(op.f('ix_friendships_requester_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_addressee_id'), table_name='friendships')
    op.drop_index('ix_friendship_addressee', table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###